In [8]:
import pandas as pd
import geopandas as gpd
import numpy as np

In [9]:
# Load the geometries
runways = gpd.read_file('engage-hackaton/runways.geojson')
thresholds = gpd.read_file('engage-hackaton/thresholds.geojson')

# Load the scenario
scenario = pd.read_parquet('engage-hackaton/samples/sample_scenario_00.parquet')
scenario

df squawk bds60_bds  bds60_heading  bds60_IAS  bds60_Mach  \
473055  20   <NA>        60     232.207031      263.0       0.776   
473056  21   4516      <NA>            NaN        NaN         NaN   
473057  21   2203      <NA>            NaN        NaN         NaN   
473058  20   <NA>      <NA>            NaN        NaN         NaN   
473059  21   6012      <NA>            NaN        NaN         NaN   
...     ..    ...       ...            ...        ...         ...   
679258  17   <NA>      <NA>            NaN        NaN         NaN   
679259  17   <NA>      <NA>            NaN        NaN         NaN   
679260  17   <NA>      <NA>            NaN        NaN         NaN   
679261  17   <NA>      <NA>            NaN        NaN         NaN   
679262  17   <NA>      <NA>            NaN        NaN         NaN   

        bds60_vrate_barometric  bds60_vrate_inertial  icao24             ts  \
473055                  -288.0                   0.0  344699  1737545255855   
473056                     NaN                   NaN  407fc1  1737545255855   
473057                     NaN                   NaN  3964f1  1737545255855   
473058                     NaN                   NaN  49514b  1737545255855   
473059                     NaN                   NaN  344345  1737545255855   
...                        ...                   ...     ...            ...   
679258                     NaN                   NaN  343141  1737545375089   
679259                     NaN                   NaN  3991e2  1737545375089   
679260                     NaN                   NaN  346384  1737545375089   
679261                     NaN                   NaN  346555  1737545375089   
679262                     NaN                   NaN  34754c  1737545375089   

        ... heading  TAS  bds30_bds  bds30_issued_ra  bds30_terminated  \
473055  ...     NaN  NaN       <NA>             <NA>              <NA>   
473056  ...     NaN  NaN       <NA>             <NA>              <NA>   
473057  ...     NaN  NaN       <NA>             <NA>              <NA>   
473058  ...     NaN  NaN       <NA>             <NA>              <NA>   
473059  ...     NaN  NaN       <NA>             <NA>              <NA>   
...     ...     ...  ...        ...              ...               ...   
679258  ...     NaN  NaN       <NA>             <NA>              <NA>   
679259  ...     NaN  NaN       <NA>             <NA>              <NA>   
679260  ...     NaN  NaN       <NA>             <NA>              <NA>   
679261  ...     NaN  NaN       <NA>             <NA>              <NA>   
679262  ...     NaN  NaN       <NA>             <NA>              <NA>   

       bds30_multiple  year  month  day  hour  
473055           <NA>  2025      1   22    11  
473056           <NA>  2025      1   22    11  
473057           <NA>  2025      1   22    11  
473058           <NA>  2025      1   22    11  
473059           <NA>  2025      1   22    11  
...               ...   ...    ...  ...   ...  
679258           <NA>  2025      1   22    11  
679259           <NA>  2025      1   22    11  
679260           <NA>  2025      1   22    11  
679261           <NA>  2025      1   22    11  
679262           <NA>  2025      1   22    11  

[45235 rows x 162 columns]

In [10]:
first_day_last_hour = pd.read_parquet('data/year=2024/month=11/day=16/hour=23/7fa82f924eb24a429fa321d057d2efd5.snappy.parquet')
first_day_last_hour

df squawk bds60_bds  bds60_heading  bds60_IAS  bds60_Mach  \
0       21   3352        60      67.148438      245.0       0.744   
1       17   None      None            NaN        NaN         NaN   
2       17   None      None            NaN        NaN         NaN   
3       20   None      None            NaN        NaN         NaN   
4       20   None      None            NaN        NaN         NaN   
...     ..    ...       ...            ...        ...         ...   
417523  20   None        60       0.527344        NaN         NaN   
417524  21   2000        60            NaN        NaN         NaN   
417525  20   None      None            NaN        NaN         NaN   
417526  20   None        60       0.527344        NaN         NaN   
417527  20   None      None            NaN        NaN         NaN   

        bds60_vrate_barometric  bds60_vrate_inertial  icao24             ts  \
0                         32.0                   0.0  4ca25a  1731798000264   
1                          NaN                   NaN  407e63  1731798000264   
2                          NaN                   NaN  3c5429  1731798000264   
3                          NaN                   NaN  4ca25a  1731798000264   
4                          NaN                   NaN  4ca9c1  1731798000264   
...                        ...                   ...     ...            ...   
417523                     NaN                   NaN  342107  1731801599678   
417524                     NaN                   0.0  342107  1731801599678   
417525                     NaN                   NaN  342107  1731801599678   
417526                     NaN                   NaN  344498  1731801599679   
417527                     NaN                   NaN  346385  1731801599679   

        ... bds05_NICb  bds05_altitude  bds05_source  bds05_parity  \
0       ...        NaN             NaN          None          None   
1       ...        NaN             NaN          None          None   
2       ...        NaN             NaN          None          None   
3       ...        NaN             NaN          None          None   
4       ...        NaN             NaN          None          None   
...     ...        ...             ...           ...           ...   
417523  ...        NaN             NaN          None          None   
417524  ...        NaN             NaN          None          None   
417525  ...        NaN             NaN          None          None   
417526  ...        NaN             NaN          None          None   
417527  ...        NaN             NaN          None          None   

       bds05_lat_cpr  bds05_lon_cpr  bds40_target_source  bds21_bds  \
0                NaN            NaN                 None       None   
1                NaN            NaN                 None       None   
2                NaN            NaN                 None       None   
3                NaN            NaN                 None       None   
4                NaN            NaN                 None       None   
...              ...            ...                  ...        ...   
417523           NaN            NaN                 None       None   
417524           NaN            NaN                 None       None   
417525           NaN            NaN                 None       None   
417526           NaN            NaN                 None       None   
417527           NaN            NaN                 None       None   

        bds21_registration bds17_bds53  
0                     None        None  
1                     None        None  
2                     None        None  
3                     None        None  
4                     None        None  
...                    ...         ...  
417523                None        None  
417524                None        None  
417525                None        None  
417526                None        None  
417527                None        None  

[417528 rows x 125 columns]

In [43]:
print(sorted(first_day_last_hour.columns.tolist()))
print(sorted(scenario.columns.tolist()))

['BAI', 'GVA', 'HRD', 'NACp', 'NACv', 'NICa', 'NICb', 'NUCp', 'SIL', 'SILs', 'TAH', 'alt_hold', 'altitude', 'approach_mode', 'autopilot', 'barometric_setting', 'bds', 'bds05_NICb', 'bds05_NUCp', 'bds05_altitude', 'bds05_lat_cpr', 'bds05_lon_cpr', 'bds05_parity', 'bds05_source', 'bds05_tc', 'bds10_acas', 'bds10_acas_hybrid', 'bds10_acas_ra', 'bds10_bds', 'bds10_config', 'bds10_dte', 'bds10_gicb', 'bds10_identification', 'bds10_level5', 'bds10_mode_s', 'bds10_ovc', 'bds10_sic', 'bds10_squitter', 'bds10_subnet', 'bds17_bds', 'bds17_bds05', 'bds17_bds06', 'bds17_bds07', 'bds17_bds08', 'bds17_bds09', 'bds17_bds0a', 'bds17_bds20', 'bds17_bds21', 'bds17_bds40', 'bds17_bds41', 'bds17_bds42', 'bds17_bds43', 'bds17_bds44', 'bds17_bds48', 'bds17_bds50', 'bds17_bds51', 'bds17_bds52', 'bds17_bds53', 'bds17_bds5f', 'bds17_bds60', 'bds20_bds', 'bds20_callsign', 'bds21_bds', 'bds21_registration', 'bds40_barometric_setting', 'bds40_bds', 'bds40_selected_fms', 'bds40_selected_mcp', 'bds40_target_source'

In [63]:
scenario.dropna(axis=1)

df  icao24             ts  year month day hour
473055  20  344699  1737545255855  2025     1  22   11
473056  21  407fc1  1737545255855  2025     1  22   11
473057  21  3964f1  1737545255855  2025     1  22   11
473058  20  49514b  1737545255855  2025     1  22   11
473059  21  344345  1737545255855  2025     1  22   11
...     ..     ...            ...   ...   ...  ..  ...
679258  17  343141  1737545375089  2025     1  22   11
679259  17  3991e2  1737545375089  2025     1  22   11
679260  17  346384  1737545375089  2025     1  22   11
679261  17  346555  1737545375089  2025     1  22   11
679262  17  34754c  1737545375089  2025     1  22   11

[45235 rows x 7 columns]

In [64]:
first_day_last_hour.dropna(axis=1)

df  icao24             ts
0       21  4ca25a  1731798000264
1       17  407e63  1731798000264
2       17  3c5429  1731798000264
3       20  4ca25a  1731798000264
4       20  4ca9c1  1731798000264
...     ..     ...            ...
417523  20  342107  1731801599678
417524  21  342107  1731801599678
417525  20  342107  1731801599678
417526  20  344498  1731801599679
417527  20  346385  1731801599679

[417528 rows x 3 columns]

In [74]:
scenario["track"].unique()

array([         nan, 212.0523213 ,   8.87328423, ..., 103.31246561,
       174.13520209,  17.54483178], shape=(1925,))

In [77]:
scenario["selected_heading"].unique()

array([       nan,   0.      , 195.46875 , 270.      , 180.      ,
        42.890625, 352.96875 , 254.53125 , 220.78125 , 217.265625,
        83.671875, 165.9375  , 149.0625  ,  35.859375, 184.21875 ,
       194.765625, 193.359375, 236.25    ,   2.8125  , 244.6875  ,
       198.28125 , 198.984375, 250.3125  ,  21.796875, 101.25    ,
       201.09375 , 170.15625 , 149.765625, 175.078125,  66.796875,
         7.734375, 151.171875, 215.15625 , 194.0625  , 108.984375,
       101.953125,  26.015625, 208.828125, 110.390625,  73.828125,
       187.03125 , 102.65625 , 186.328125, 109.6875  , 258.75    ,
       167.34375 , 185.625   , 196.875   ,  25.3125  , 191.953125,
       188.4375  , 187.734375, 104.0625  , 245.390625, 255.234375,
       189.140625,  45.703125, 257.34375 , 199.6875  ,  30.9375  ,
       206.015625,  59.0625  ,  85.078125, 200.390625,  26.71875 ,
       197.578125, 172.96875 , 246.09375 ,  57.65625 , 111.09375 ,
       196.171875, 190.546875, 191.25    , 189.84375 , 239.765

In [79]:
scenario["bds60_heading"].unique()

array([2.32207031e+02,            nan, 3.54550781e+02, 2.52773438e+02,
       1.58203125e+00, 2.66308594e+02, 2.53125000e+01, 6.66210938e+01,
       4.92187500e+00, 1.49062500e+02, 1.51171875e+01, 1.83691406e+02,
       1.87382812e+02, 1.89316406e+02, 3.58242188e+02, 2.95664062e+02,
       1.93359375e+00, 2.52597656e+02, 2.17968750e+02, 2.74218750e+02,
       1.93183594e+02, 1.99335938e+02, 1.52929688e+01, 2.45917969e+02,
       1.66464844e+02, 3.03925781e+02, 2.16210938e+01, 2.17968750e+01,
       3.70898438e+01, 3.53144531e+02, 2.23066406e+02, 3.84960938e+01,
       3.58769531e+02, 6.67968750e+01, 3.69140625e+01, 2.74394531e+02,
       2.31855469e+02, 2.44335938e+02, 2.21484375e+02, 1.70156250e+02,
       2.28515625e+00, 9.07031250e+01, 2.54531250e+02, 1.82109375e+02,
       3.18164062e+01, 2.21308594e+02, 2.19726562e+02, 2.54882812e+01,
       2.65429688e+02, 2.44511719e+02, 3.03574219e+02, 3.59472656e+02,
       2.49785156e+02, 2.83007812e+02, 1.99160156e+02, 9.21093750e+01,
      

In [78]:
scenario["bds50_track"].unique()

array([         nan,  66.796875  , 219.375     , 357.01171875,
       230.80078125, 280.72265625,  36.38671875, 255.76171875,
       181.23046875,  43.06640625,  17.578125  ,  24.43359375,
       307.08984375, 307.265625  , 243.10546875,  97.91015625,
       184.74609375,  24.609375  , 244.86328125, 286.69921875,
        65.7421875 , 263.14453125, 179.47265625,   8.7890625 ,
         4.921875  , 307.6171875 ,  89.296875  ,  20.7421875 ,
       265.078125  , 229.39453125, 174.7265625 ,   8.96484375,
        65.91796875,  66.97265625,  23.203125  , 212.87109375,
       203.37890625,   7.20703125, 190.546875  , 217.79296875,
        31.11328125, 157.67578125, 300.9375    , 217.6171875 ,
       205.48828125,   0.        , 193.53515625, 221.8359375 ,
       179.82421875, 307.44140625,  20.91796875, 142.20703125,
       190.1953125 ,  29.8828125 , 244.16015625, 286.5234375 ,
       254.1796875 ,  20.0390625 , 184.5703125 ,  33.75      ,
       209.35546875, 206.015625  , 230.625     , 174.37

In [80]:
scenario["bds45_radio_height"].unique()

array([   nan,     0., 65024., 56944., 65136.])

In [70]:
scenario["groundspeed"].unique()

array([         nan, 388.17135391, 479.74159711, ..., 364.80268639,
       332.74164152, 447.83255799], shape=(1886,))

In [73]:
scenario["bds50_groundspeed"].unique()

array([ nan, 508., 400., 452., 380., 306., 402., 388.,  46., 344., 512.,
       484., 434., 404., 252., 418., 430., 398., 444.,  10., 478., 474.,
       374., 496., 228., 290., 326., 506., 482., 396., 240., 476., 372.,
       192., 390., 494., 334., 382., 244., 416., 406., 218., 442.,   6.,
         0., 256., 480., 312., 350., 386., 392., 490., 534., 424.,  36.,
       436., 486., 330., 428., 384., 530., 446., 348., 408., 176., 236.,
       346., 206., 450., 504., 394., 426., 532., 270., 454., 180., 500.,
       468., 536.,  18., 456., 190., 170., 410., 432., 324., 356., 492.,
       470., 502., 420., 188., 460., 172.,  14., 360., 522., 210., 422.,
       212.,  12., 242., 168., 378., 510., 196., 292., 310., 294.,  24.,
       222., 220., 296., 214., 314., 254., 514., 316., 488., 130., 208.,
       302., 132., 174.,   2.,  28., 370., 322., 438., 286., 158., 472.,
       238., 200., 538., 328., 364., 516., 164., 440., 308., 354., 318.,
       300., 248., 178., 246., 280., 376., 320.,   

In [137]:
first_day_last_hour["groundspeed"]["bds"]

array([         nan, 467.64195706,  21.        , ..., 160.41508657,
       154.45711379, 287.00174215], shape=(9565,))

In [130]:
first_day_last_hour[first_day_last_hour['df'] == '17']

df squawk bds60_bds  bds60_heading  bds60_IAS  bds60_Mach  \
1       17   None      None            NaN        NaN         NaN   
2       17   None      None            NaN        NaN         NaN   
10      17   None      None            NaN        NaN         NaN   
11      17   None      None            NaN        NaN         NaN   
17      17   None      None            NaN        NaN         NaN   
...     ..    ...       ...            ...        ...         ...   
417517  17   None      None            NaN        NaN         NaN   
417519  17   None      None            NaN        NaN         NaN   
417520  17   None      None            NaN        NaN         NaN   
417521  17   6273      None            NaN        NaN         NaN   
417522  17   None      None            NaN        NaN         NaN   

        bds60_vrate_barometric  bds60_vrate_inertial  icao24             ts  \
1                          NaN                   NaN  407e63  1731798000264   
2                          NaN                   NaN  3c5429  1731798000264   
10                         NaN                   NaN  341682  1731798000264   
11                         NaN                   NaN  3c5429  1731798000264   
17                         NaN                   NaN  e80447  1731798000264   
...                        ...                   ...     ...            ...   
417517                     NaN                   NaN  4ac8f6  1731801599678   
417519                     NaN                   NaN  407797  1731801599678   
417520                     NaN                   NaN  347519  1731801599678   
417521                     NaN                   NaN  502ce3  1731801599678   
417522                     NaN                   NaN  34644c  1731801599678   

        ... bds05_NICb  bds05_altitude  bds05_source  bds05_parity  \
1       ...        NaN             NaN          None          None   
2       ...        NaN             NaN          None          None   
10      ...        NaN             NaN          None          None   
11      ...        NaN             NaN          None          None   
17      ...        NaN             NaN          None          None   
...     ...        ...             ...           ...           ...   
417517  ...        NaN             NaN          None          None   
417519  ...        NaN             NaN          None          None   
417520  ...        NaN             NaN          None          None   
417521  ...        NaN             NaN          None          None   
417522  ...        NaN             NaN          None          None   

       bds05_lat_cpr  bds05_lon_cpr  bds40_target_source  bds21_bds  \
1                NaN            NaN                 None       None   
2                NaN            NaN                 None       None   
10               NaN            NaN                 None       None   
11               NaN            NaN                 None       None   
17               NaN            NaN                 None       None   
...              ...            ...                  ...        ...   
417517           NaN            NaN                 None       None   
417519           NaN            NaN                 None       None   
417520           NaN            NaN                 None       None   
417521           NaN            NaN                 None       None   
417522           NaN            NaN                 None       None   

        bds21_registration bds17_bds53  
1                     None        None  
2                     None        None  
10                    None        None  
11                    None        None  
17                    None        None  
...                    ...         ...  
417517                None        None  
417519                None        None  
417520                None        None  
417521                None        None  
417522                None        None  

[218119 rows x 125 columns]

In [96]:
scenario.plot("altitude", "lon_deg", "lat_deg")

ValueError: lat_deg is not a valid plot kind Valid plot kinds: ('line', 'bar', 'barh', 'kde', 'density', 'area', 'hist', 'box', 'pie', 'scatter', 'hexbin')

In [98]:
scenario.dropna(axis=1, how='all')

df squawk bds60_bds  bds60_heading  bds60_IAS  bds60_Mach  \
473055  20   <NA>        60     232.207031      263.0       0.776   
473056  21   4516      <NA>            NaN        NaN         NaN   
473057  21   2203      <NA>            NaN        NaN         NaN   
473058  20   <NA>      <NA>            NaN        NaN         NaN   
473059  21   6012      <NA>            NaN        NaN         NaN   
...     ..    ...       ...            ...        ...         ...   
679258  17   <NA>      <NA>            NaN        NaN         NaN   
679259  17   <NA>      <NA>            NaN        NaN         NaN   
679260  17   <NA>      <NA>            NaN        NaN         NaN   
679261  17   <NA>      <NA>            NaN        NaN         NaN   
679262  17   <NA>      <NA>            NaN        NaN         NaN   

        bds60_vrate_barometric  bds60_vrate_inertial  icao24             ts  \
473055                  -288.0                   0.0  344699  1737545255855   
473056                     NaN                   NaN  407fc1  1737545255855   
473057                     NaN                   NaN  3964f1  1737545255855   
473058                     NaN                   NaN  49514b  1737545255855   
473059                     NaN                   NaN  344345  1737545255855   
...                        ...                   ...     ...            ...   
679258                     NaN                   NaN  343141  1737545375089   
679259                     NaN                   NaN  3991e2  1737545375089   
679260                     NaN                   NaN  346384  1737545375089   
679261                     NaN                   NaN  346555  1737545375089   
679262                     NaN                   NaN  34754c  1737545375089   

        ... bds17_bds42  bds17_bds44  bds17_bds48  bds21_bds  \
473055  ...        <NA>         <NA>         <NA>       <NA>   
473056  ...        <NA>         <NA>         <NA>       <NA>   
473057  ...        <NA>         <NA>         <NA>       <NA>   
473058  ...        <NA>         <NA>         <NA>       <NA>   
473059  ...        <NA>         <NA>         <NA>       <NA>   
...     ...         ...          ...          ...        ...   
679258  ...        <NA>         <NA>         <NA>       <NA>   
679259  ...        <NA>         <NA>         <NA>       <NA>   
679260  ...        <NA>         <NA>         <NA>       <NA>   
679261  ...        <NA>         <NA>         <NA>       <NA>   
679262  ...        <NA>         <NA>         <NA>       <NA>   

        bds21_registration bds17_bds45  year  month  day  hour  
473055                <NA>        <NA>  2025      1   22    11  
473056                <NA>        <NA>  2025      1   22    11  
473057                <NA>        <NA>  2025      1   22    11  
473058                <NA>        <NA>  2025      1   22    11  
473059                <NA>        <NA>  2025      1   22    11  
...                    ...         ...   ...    ...  ...   ...  
679258                <NA>        <NA>  2025      1   22    11  
679259                <NA>        <NA>  2025      1   22    11  
679260                <NA>        <NA>  2025      1   22    11  
679261                <NA>        <NA>  2025      1   22    11  
679262                <NA>        <NA>  2025      1   22    11  

[45235 rows x 126 columns]

In [102]:
sorted(scenario.dropna(axis=1, how='all').columns.tolist())

['BAI',
 'GVA',
 'HRD',
 'NACp',
 'NACv',
 'NICa',
 'NICb',
 'NUCp',
 'SIL',
 'SILs',
 'TAH',
 'alt_hold',
 'altitude',
 'approach_mode',
 'autopilot',
 'barometric_setting',
 'bds',
 'bds05_NICb',
 'bds05_NUCp',
 'bds05_altitude',
 'bds05_lat_cpr',
 'bds05_lon_cpr',
 'bds05_parity',
 'bds05_source',
 'bds05_tc',
 'bds10_acas',
 'bds10_acas_hybrid',
 'bds10_acas_ra',
 'bds10_bds',
 'bds10_config',
 'bds10_dte',
 'bds10_gicb',
 'bds10_identification',
 'bds10_level5',
 'bds10_mode_s',
 'bds10_ovc',
 'bds10_sic',
 'bds10_squitter',
 'bds10_subnet',
 'bds17_bds',
 'bds17_bds05',
 'bds17_bds06',
 'bds17_bds07',
 'bds17_bds08',
 'bds17_bds09',
 'bds17_bds0a',
 'bds17_bds20',
 'bds17_bds21',
 'bds17_bds40',
 'bds17_bds41',
 'bds17_bds42',
 'bds17_bds44',
 'bds17_bds45',
 'bds17_bds48',
 'bds17_bds50',
 'bds17_bds51',
 'bds17_bds52',
 'bds17_bds53',
 'bds17_bds5f',
 'bds17_bds60',
 'bds20_bds',
 'bds20_callsign',
 'bds21_bds',
 'bds21_registration',
 'bds40_barometric_setting',
 'bds40_bds',
